cargo-features = ["edition"]

[package]
name = "test_runner"
version = "0.1.0"
authors = ["aticu <15schnic@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
tempfile = "3.0.3"
wait-timeout = "0.1.5"